/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Cntrl.Control;
import ON.Barco;
import ON.Salida;
import ON.Socio;

/**
 *
 * @author Luis
 */
public class FrmBarcos extends javax.swing.JFrame {

    /**
     * Creates new form FrmBarcos
     */
    private Control control;
    
    public FrmBarcos() {
        initComponents();
        this.control = new Control();
        this.cargarBarcos();
        this.cargarSocioComboBox();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblNumamarre = new javax.swing.JLabel();
        lblCuota = new javax.swing.JLabel();
        lblSocio = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNumamarre = new javax.swing.JTextField();
        txtCuota = new javax.swing.JTextField();
        cboxSocio = new javax.swing.JComboBox();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        panBarcos = new javax.swing.JScrollPane();
        tblBarcos = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Catálogo de Barcos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblId.setText("ID");

        lblMatricula.setText("MATRICULA");

        lblNombre.setText("NOMBRE");

        lblNumamarre.setText("NUM. AMARRE");

        lblCuota.setText("CUOTA");

        lblSocio.setText("SOCIO");

        txtId.setEditable(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        cboxSocio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tblBarcos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "MATRICULA", "NOMBRE", "NUM. AMARRE", "CUOTA", "SOCIO", "SOCIO ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        panBarcos.setViewportView(tblBarcos);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId)
                            .addComponent(lblMatricula)
                            .addComponent(lblNombre))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMatricula)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumamarre)
                            .addComponent(lblCuota)
                            .addComponent(lblSocio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar)
                                .addGap(0, 38, Short.MAX_VALUE))
                            .addComponent(txtNumamarre)
                            .addComponent(txtCuota)
                            .addComponent(cboxSocio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBusqueda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar))
                    .addComponent(panBarcos, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panBarcos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBorrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMatricula)
                                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNombre)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNumamarre)
                                    .addComponent(txtNumamarre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCuota)
                                    .addComponent(txtCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSocio)
                                    .addComponent(cboxSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnGuardar)
                                    .addComponent(btnCancelar))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(this.txtId.getText().equals("0")){
            this.guardarBarco();
        }else{
            this.actualizarBarco();
        } 
        this.limpiarFormulario();
        this.cargarBarcos();
        this.cargarSocioComboBox();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limpiarFormulario();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        this.cargarBarcos();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        this.cargarBarco();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        this.eliminarBarco();
        this.cargarBarcos();
        this.cargarSocioComboBox();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        FrmMenu pantallaInicio = new FrmMenu();
        pantallaInicio.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBarcos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBarcos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBarcos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBarcos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBarcos().setVisible(true);
            }
        });
    }
    
    private void cargarBarcos() {
        List<Barco> barcos = this.control.obtenerBarcos(txtBusqueda.getText());
        if (barcos != null) {
            DefaultTableModel modelo
                    = (DefaultTableModel) tblBarcos.getModel();
            modelo.setRowCount(0);
            for (Barco barco : barcos) {
                modelo.addRow(barco.toArray());
            }
        }
    }
    
    private void cargarSocioComboBox() {
        List<Socio> socios = this.control.obtenerSociosComboBox();
        if (socios != null) {
            cboxSocio.removeAllItems();
            for (Socio socio : socios) {
                cboxSocio.addItem(socio);
            }
        }
    }
    
    private void limpiarFormulario() {
        txtId.setText("0");
        txtMatricula.setText("");
        txtNombre.setText("");
        txtNumamarre.setText("");
        txtCuota.setText("");
        txtBusqueda.setText("");
    }
    
    private void guardarBarco() {
        Barco barco = new Barco();
        barco.setMatricula(txtMatricula.getText());
        barco.setNombre(txtNombre.getText());
        barco.setNumAmarre(Integer.parseInt(txtNumamarre.getText()));
        barco.setCuota(Float.valueOf(txtCuota.getText()));
        barco.setNombreSocio(((Socio)cboxSocio.getSelectedItem()).getNombre());
        barco.setIdsocios(((Socio)cboxSocio.getSelectedItem()).getId());
        
        this.control.guardarBarco(barco);
    }
    
    private void actualizarBarco() {
        Barco barco = new Barco();
        barco.setIdbarcos(Integer.parseInt(txtId.getText()));
        barco.setMatricula(txtMatricula.getText());
        barco.setNombre(txtNombre.getText());
        barco.setNumAmarre(Integer.parseInt(txtNumamarre.getText()));
        barco.setCuota(Float.valueOf(txtCuota.getText()));
        barco.setNombreSocio(((Socio)cboxSocio.getSelectedItem()).getNombre());
        barco.setIdsocios(((Socio)cboxSocio.getSelectedItem()).getId());
        
        this.control.actualizarBarco(barco);
    }
    
    private void eliminarBarco(){
        int fila = this.tblBarcos.getSelectedRow();
        if(fila == -1){
            JOptionPane.showMessageDialog(this, "Debes seleccionar un barco", 
                    "Información", JOptionPane.INFORMATION_MESSAGE);
        }else{
            DefaultTableModel modelo = (DefaultTableModel)this.tblBarcos.getModel();
            Integer idBarco = (Integer)modelo.getValueAt(fila, 0);
            boolean eliminacionExitosa = this.control.eliminarBarco(idBarco);
            if(eliminacionExitosa){
                JOptionPane.showMessageDialog(this, "Barco eliminado correctamente", 
                        "Información", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo eliminar el barco",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }                
    }
    
    private void cargarBarco(){
        int fila = this.tblBarcos.getSelectedRow();
        if(fila == -1){
            JOptionPane.showMessageDialog(this, "Debes seleccionar un barco", 
                    "Información", JOptionPane.INFORMATION_MESSAGE);
        }else{
            DefaultTableModel modelo = (DefaultTableModel)this.tblBarcos.getModel();
            Integer idBarco = (Integer)modelo.getValueAt(fila, 0);
            Barco barco = control.obtenerBarcoPorId(idBarco);
            if(barco != null){
                txtId.setText(String.valueOf(barco.getIdbarcos()));
                txtMatricula.setText(barco.getMatricula());
                txtNombre.setText(barco.getNombre());
                txtNumamarre.setText(String.valueOf(barco.getNumAmarre()));
                txtCuota.setText(String.valueOf(barco.getCuota()));
                cboxSocio.setSelectedItem(control.obtenerSocioPorId(barco.getIdsocios()));
            }else{
                JOptionPane.showMessageDialog(this, "No se encontró el barco", 
                        "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cboxSocio;
    private javax.swing.JLabel lblCuota;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumamarre;
    private javax.swing.JLabel lblSocio;
    private javax.swing.JScrollPane panBarcos;
    private javax.swing.JTable tblBarcos;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCuota;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumamarre;
    // End of variables declaration//GEN-END:variables
}
